[project]
name = "bmd-hs-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ivan Steiger", email = "isteiger@student.ethz.ch" }
]
requires-python = ">=3.12"
dependencies = [
    "librosa>=1.0.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "torch>=2.13.0",
    "torchaudio>=2.11.0",
    "torchcodec>=0.16.0",
]

[project.scripts]
bmd-hs-dataset = "bmd_hs_dataset:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
